name: CI

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, reopened, synchronize]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build-and-test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, ubuntu-24.04-arm, macos-latest]
        compiler: ['gcc', 'clang']
        exclude:
          - os: macos-latest
            compiler: gcc

    runs-on: ${{ matrix.os }}

    env:
      CC: ${{ matrix.compiler }}

    steps:
      - uses: actions/checkout@v4
      - name: Log compiler version
        run: |
          "$CC" --version
      - name: Set up CMake
        uses: jwlawson/actions-setup-cmake@v1
      - name: Set up Ninja (Linux/macOS)
        if: runner.os != 'Windows'
        uses: ashutoshvarma/setup-ninja@master
      - name: Configure CMake
        run: cmake -S . -B build -G Ninja -DIMATH_ENABLE_TESTING=ON
      - name: Build
        run: cmake --build build
      - name: Run tests
        run: ctest --test-dir build --output-on-failure
